title: "EHMI - Enhanced Healthcare Messaging Infrastructure"
logo: /assets/images/EHMI-MedCom_logo_104x89.png
description: "Enhanced Healthcare Messaging Infrastructure"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
version: "Version 0.9.0"
fhir_version: "EHMI"
releasenote: https://github.com/medcomdk/ehmi/releases
thisurl: https://medcomdk.github.io/ehmi/
menuurl_item1: https://medcomdk.github.io/ehmi/
menutxt_item1: EHMI Landingpage
menuurl_item2: https://medcomdk.github.io/ehmi/assets/documents/ecore/
menutxt_item2: EHMI Core
menuurl_item3: https://medcomdk.github.io/ehmi/assets/documents/eds/
menutxt_item3: EHMI Delivery Status
menuurl_item4: https://medcomdk.github.io/ehmi/assets/documents/eas/
menutxt_item4: EHMI Addressing Service*
menuurl_item5: https://medcomdk.github.io/ehmi/assets/documents/eer/
menutxt_item5: EHMI Endpoint Register*
menuurl_item6: https://medcomdk.github.io/ehmi/assets/documents/egov/
menutxt_item6: EHMI Governance*
menuurl_item7: https://medcomdk.github.io/ehmi/assets/documents/security/
menutxt_item7: EHMI Security
menuurl_item8: https://medcomdk.github.io/ehmi/assets/documents/glossary/
menutxt_item8: EHMI Glossary
menuurl_item9: https://medcomdk.github.io/ehmi/assets/documents/ehmi_ecosystem.html
menutxt_item9: EHMI Ecosystem
